### ISSUE TITLE
Tran UI quits on typing q in password box

### ISSUE THREAD

**Issue by mattiasbonte** [abdfnx/tran#38]
Hello,

When typing in the receiver password in the tran UI, the application quits upon typing q.

Expected behavior is to see the the ui's keybinds disabled when typing in the password?

Cheers!

**Comment by abdfnx** [comment]
ok, I will fix it right now

**Comment by abdfnx** [comment]
fixed in tran version `v0.1.4`

**Comment by mattiasbonte** [comment]
Hey, thanks! Btw, just a thought, but wouldn't it be better instead of deleting the q key, making it so that when using the password prompt the keymaps are ignored?

The reason why I like the q key is because a lot of cli apps. (ex lazygit, lazydocker, nnn...) all use q as a keybind for quitting the application.

**Comment by abdfnx** [comment]
Hmmmm, it's a great idea, I will work on it

**Comment by abdfnx** [comment]
done, checkout the new version of tran `v0.1.41`
