### ISSUE TITLE
Tran on Windows complains about config file not being found in wrong directory

### ISSUE THREAD

**Issue by soda3x** [abdfnx/tran#42]
when running `tran` from Powershell, the following is displayed:

`2022/08/02 10:21:19 Config File "tran" Not Found in "[C:\\.config\\tran]"`

My `tran.yml` file is situated in `~/.config/tran` as per the instructions.

I don't think it should be trying to find the .config file at the root of the C drive?

**Comment by soda3x** [comment]
Could this be that in config.go, `$HOME` is being used instead of `$USERPROFILE` for Windows configurations?

**Comment by abdfnx** [comment]
Ok, no problem, I'm going to fix it

**Comment by abdfnx** [comment]
@soda3x checkout the new version of `tran`

**Comment by abdfnx** [comment]
@soda3x is every thing okay ?

**Comment by soda3x** [comment]
Hmm, no dice unfortunately.
I'm presented with a similar error:
`2022/08/04 09:10:58 Config File "tran" Not Found in "[C:\\.tran C:\\Users\\username\\.tran]"`

It's progress though because that second path is where it should be!

**Comment by soda3x** [comment]
I have opened a PR: #44 to action this issue

**Comment by abdfnx** [comment]
@soda3x checkout the new version `v0.1.43`

**Comment by soda3x** [comment]
Seems like it's working now! :)

**Comment by abdfnx** [comment]
nice, thanks for fixing this bug
