### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by mmacheerpuppy** [abdfnx/tran#6]
Curious how systems are discovered running TranUI. From what I see there's just a password involved. What about destination IP?

**Comment by abdfnx** [comment]
the default **IP** address of TranUI is `167.71.65.96`

**Comment by mmacheerpuppy** [comment]
@abdfnx so what data gets sent to that IP?

**Comment by abdfnx** [comment]
is everything okay @mmacheerpuppy ?
